# Generated by Django 3.1.7 on 2021-03-29 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_sessionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_session_requests', to='backend.subject'),
        ),
    ]
