# Generated by Django 3.1.7 on 2021-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210329_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
