# Generated by Django 3.1.7 on 2021-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sessionrequest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='accepted_tutors',
            field=models.ManyToManyField(related_name='accepted_sessions', to='backend.Tutor'),
        ),
    ]
