# Generated by Django 3.1.7 on 2021-06-22 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210622_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='description',
            field=models.CharField(default='Session Description', max_length=200, verbose_name='symptom description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='backend.sessionrequest'),
            preserve_default=False,
        ),
    ]
