# Generated by Django 3.1.7 on 2021-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210622_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount_owed',
            field=models.FloatField(default=0),
        ),
    ]
