# Generated by Django 3.1.7 on 2021-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_student_amount_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='report',
            field=models.CharField(default='', max_length=500, verbose_name='report text'),
        ),
    ]
